export enum CommonExceptionCodes {
    NOT_FOUND = 'NOT_FOUND',
    RECORD_EXISTING = 'RECORD_EXISTING',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    TRANSACTION_FAILED = 'TRANSACTION_FAILED',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE'
}
